import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
// import Provider from "@/provider";

const Outfito = Outfit({subsets:['latin']})

export const metadata = {
  title: "@viishall.01",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
          <html lang="en">
      <body className={Outfito.className }>
      
          {/* <Provider> */}
            {children}
          {/* </Provider> */}
      </body>
    </html>
    // </ClerkProvider>

  );
}
